package mp.app.calonex.tenant.model

data class InvoiceDetailsDao(
    var discount: String?,
    val dueAmount: Double,
    val dueDate: String,
    val duration: String,
    val emailAddress: String,
    val finalAmount: String,
    val fromAddress: String,
    val fromEmailAddress: String,
    val fromMobileNo: String,
    val fromName: String,
    val invoiceChargeList: List<InvoiceCharge>,
    val invoiceDate: String,
    val invoiceId: Int,
    val invoiceType: String,
    val leaseId: Int,
    val mobileNo: String,
    val name: String,
    val paidAmount: String,
    val paymentDate: Any,
    val planAmount: Any,
    val planName: Any,
    val previousOutstanding: Double,
    val propertyAddress: String,
    val propertyId: String,
    val propertyUnitNo: String,
    val referanceNumber: String,
    val rentAmount: String,
    val securityDeposit: String,
    val serviceFee: String,
    val status: String,
    val subscriptionId: Any,
    val totalCharge: String,
    val totalTax: Double,
    val userCatalogId: Int
)