package mp.app.calonex.tenant.model

data class TenantRentInfo(
    val totalRentAmount: String = "",
    val totalSecurityAmount: String = "",
    val totalPayableAmount: String = "",
    val monthlyRentResponsibility: String = "",
    val securityResponsibility: String = "",
    val rentPercentage: String = "",
    val rentDueDate: String = "",
    val rentDueDay: String = "",
    val rentDueMonth: String = "",
    val rentDueYear: String = "",
    val nextRentDate: String = "",
    val bankAccountNumber: String = "",
    val routingNumber: String = "",
    val autoPay: Boolean = false,
    val breakup: RentBreakup = RentBreakup(),
    var amenities: String="",
    var currentLocalDate: Long=0,
    var discount: String="",
    var dueAmount: String="",
    var landlordServiceFee:String="",
    var lateFee:String="",
    var leaseId:String="",
    var monthlyRentResponsibilityBeforeDueDate:String="",
    var payableSecurity:String="",
    var paybleRent:String="",
    var paymentStatus:String="",
    var tenantServiceFee:String="",
    var tenantId:String="",
    )
