package mp.app.calonex.landlord.model

data class UnitDetailsPD(
    var propertyUnitID: String,
    var propertyID: String,
    var unitType: String,
    var unitNumber: String,
    var rentPerMonth: String,
    var dateOfAvailibility: String,
    var squareFootArea: String,
    var bathroomTypeID: String,
    var lastPaymentDate: String,
    var tenantFirstName: String,
    var tenantMiddleName: String,
    var tenantLastName: String,
    var tenantEmailId: String,
    var tenantPhoneNumber: String,
    var rentDue: String,
    var published: Boolean=false,
    var unitTypeId: String,
    var bathroomTypeName: String,
    var unitFeatureDTO:  ArrayList<UnitFeaturePD>,
    var unitUtilitiesDTO:  ArrayList<UnitUtilityPD>,
    var unitStatus : String,
    var monthsFree : String,
    var securityAmount : String,
    var leaseStartDate : String,
    var rentBeforeDueDate : String,
    var lateFee : String,
    var canAddNewLease: Boolean,
    var canRenewalLease: Boolean,
    var increaseYearlyPercentage: String,
    var applicationFees: String,
    var discount: String,
    var fileList: ArrayList<FetchDocumentModel>
    )